import React from 'react';
import { Box, List, ListItem, ListItemButton, ListItemText, Typography } from '@mui/material';
import { type HeadingData } from '../lib/remark-extract-headings.ts'; // Import the type, added .ts extension

interface TableOfContentsProps {
  headings: HeadingData[];
  onLinkClick?: () => void; // Optional callback for when a link is clicked (e.g., to close mobile drawer)
}

export const TableOfContents: React.FC<TableOfContentsProps> = ({ headings, onLinkClick }) => {
  if (!headings || headings.length === 0) {
    return null; // Don't render anything if there are no headings
  }

  const handleLinkClick = () => { // Removed unused 'event' parameter
    // Prevent default if necessary, or just call the callback
    if (onLinkClick) {
      onLinkClick();
    }
    // Allow default anchor behavior to navigate
  };

  return (
    <Box sx={{ width: '100%', maxWidth: 360, bgcolor: 'background.paper', p: 1 }}>
      <Typography variant="overline" sx={{ pl: 2, display: 'block', mb: 1 }}>
        On this page
      </Typography>
      <List dense component="nav" aria-label="table of contents">
        {headings.map((heading) => (
          <ListItem key={heading.slug} disablePadding sx={{ pl: (heading.depth - 1) * 2 }}> {/* Indent based on depth */}
            <ListItemButton
              component="a"
              href={`#${heading.slug}`} // Link to the ID generated by rehype-slug
              onClick={handleLinkClick}
              sx={{ py: 0.5 }} // Adjust padding
            >
              <ListItemText primary={heading.text} primaryTypographyProps={{ variant: 'body2' }} />
            </ListItemButton>
          </ListItem>
        ))}
      </List>
    </Box>
  );
};

export default TableOfContents;
